#!/usr/bin/env bash
set -euo pipefail

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is required but not installed." >&2
  exit 1
fi

OWNER="${1:-}"
if [[ -z "$OWNER" ]]; then
  OWNER="$(gh api user --jq .login 2>/dev/null || true)"
fi
if [[ -z "$OWNER" ]]; then
  echo "GitHub owner is required. Pass as first argument: ./scripts/sync_github_repos.sh <owner>" >&2
  exit 1
fi
LIMIT="${REPO_LIMIT:-200}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="$ROOT_DIR/docs/projects/data"
JSON_FILE="$DATA_DIR/public-repos.json"
MD_FILE="$ROOT_DIR/docs/projects/public-repos.md"

mkdir -p "$DATA_DIR"

# Machine-readable data source for future rendering enhancements.
gh repo list "$OWNER" --limit "$LIMIT" \
  --json name,description,url,updatedAt,primaryLanguage,isPrivate,isArchived \
  --jq 'map(select(.isPrivate == false and .isArchived == false) | {
    name,
    description: (if .description == null or .description == "" then "-" else .description end),
    url,
    updatedAt,
    language: (if .primaryLanguage == null or .primaryLanguage.name == null or .primaryLanguage.name == "" then "-" else .primaryLanguage.name end)
  }) | sort_by(.updatedAt) | reverse' > "$JSON_FILE"

# Human-readable markdown table included by docs/projects/index.md.
{
  echo "<!-- Generated by scripts/sync_github_repos.sh. Do not edit manually. -->"
  echo
  echo "| Repository | Language | Updated (UTC) | Description |"
  echo "|---|---|---|---|"

  while IFS=$'\t' read -r name language updated description url; do
    [ -z "$name" ] && continue
    description="${description//|/\\|}"
    description="${description//$'\n'/ }"
    printf "| [%s](%s) | %s | %s | %s |\n" "$name" "$url" "$language" "$updated" "$description"
  done < <(
    gh repo list "$OWNER" --limit "$LIMIT" \
      --json name,description,url,updatedAt,primaryLanguage,isPrivate,isArchived \
      --jq 'map(
          select(.isPrivate == false and .isArchived == false) | {
            name,
            language: (if .primaryLanguage == null or .primaryLanguage.name == null or .primaryLanguage.name == "" then "-" else .primaryLanguage.name end),
            updatedAt,
            description: (if .description == null or .description == "" then "-" else .description end),
            url
          }
        )
        | sort_by(.updatedAt)
        | reverse
        | .[]
        | [.name, .language, .updatedAt, .description, .url]
        | @tsv'
  )

  echo
  echo "_Last refreshed: $(date -u +"%Y-%m-%d %H:%M:%SZ")_"
} > "$MD_FILE"

echo "Wrote $JSON_FILE"
echo "Wrote $MD_FILE"
